name: basic_cleaning
dependencies:
  - python=3.6
  - pip=20.3.3
  - pip:
      - wandb==0.10.21
      - pandas
      - mlflow==1.14.1
      - scikit-learn==0.24.1
      - matplotlib
      - pillow==8.1.2
