name: test_regression_model
dependencies:
  - python=3.6
  - pip=20.3.3
  - pip:
      - wandb==0.10.31
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
      - pandas==1.1.4
      - mlflow==1.14.1
      - scikit-learn==0.24.1
